=== Guts/qgis-deployment-cli/docs/schemas/profile/qgis_profile.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/Guts/qgis-deployment-cli/raw/main/docs/schemas/profile/qgis_profile.json",
    "$comment": "A QGIS profile described in a JSON file in the QDT formalism.",
    "type": "object",
    "properties": {
        "alias": {
            "description": "Profile's name in an human readable form, allowing special characters.",
            "type": "string"
        },
        "author": {
            "description": "Name of profile auhor and maintener.",
            "type": "string"
        },
        "description": {
            "description": "Profile description.",
            "type": "string"
        },
        "email": {
            "description": "Email of profile's auhor and maintener.",
            "format": "email",
            "maxLength": 127,
            "minLength": 6,
            "type": "string"
        },
        "folder_name": {
            "description": "Name of the profile's directory in QGIS.",
            "type": "string"
        },
        "icon": {
            "description": "Relative path to the icon used for shortcuts.",
            "type": "string"
        },
        "name": {
            "description": "Profile name without any special characters.",
            "type": "string"
        },
        "plugins": {
            "description": "Plugins installed with the profile.",
            "title": "QGIS Plugins",
            "type": "array",
            "items": {
                "$ref": "qgis_plugin.json"
            }
        },
        "qgisMaximumVersion": {
            "description": "Maximum QGIS version where the profile can be deployed. It should complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        },
        "qgisMinimumVersion": {
            "description": "Minimum QGIS version where the profile can be deployed. It should complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        },
        "rules": {
            "description": "Logical rules based on contextual elements that condition profile deployment.",
            "title": "QGIS Plugins",
            "type": "array",
            "items": {
                "$ref": "rules.json"
            }
        },
        "splash": {
            "description": "Relative path to the splash image.",
            "type": "string"
        },
        "version": {
            "description": "Profile version. Must complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        }
    },
    "required": [
        "author",
        "email",
        "name",
        "version"
    ]
}

=== Guts/qgis-deployment-cli/tests/fixtures/profiles/good_sample_profile.json
{
    "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
    "name": "demo_qdt",
    "folder_name": "demo_qdt",
    "description": "QGIS profile made to demonstrate how QGIS Deployement Toolbelt works.",
    "author": "Julien Moura",
    "email": "qgis@oslandia.com",
    "icon": "images/qgis_icon_oslandia.ico",
    "qgisMinimumVersion": "3.24",
    "qgisMaximumVersion": "3.99",
    "version": "1.1.0",
    "plugins": [
        {
            "name": "Layers menu from project",
            "folder_name": "menu_from_project",
            "official_repository": true,
            "plugin_id": 43,
            "version": "v2.0.6"
        },
        {
            "name": "QuickOSM",
            "folder_name": "QuickOSM",
            "location": "remote",
            "official_repository": true,
            "plugin_id": 2733,
            "version": "2.1.1"
        },
        {
            "name": "QTribu",
            "folder_name": "qtribu",
            "official_repository": true,
            "plugin_id": 2733,
            "version": "0.14.2"
        }
    ]
}

=== Guts/qgis-deployment-cli/examples/profiles/Viewer Mode/profile.json
{
  "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "QDT Viewer Mode",
  "folder_name": "qdt_viewer_mode",
  "description": "Demo QGIS profile for QDT customized for end-users which are only viewers.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "icon": "images/logo_qdt.ico",
  "qgisMinimumVersion": "3.28.0",
  "qgisMaximumVersion": "3.99.10",
  "version": "1.0.0",
  "plugins": [
    {
      "name": "Profile Manager",
      "folder_name": "profile-manager",
      "official_repository": true,
      "plugin_id": 2515,
      "version": "0.31"
    }
  ]
}

=== Guts/qgis-deployment-cli/examples/demo/profile.json
{
  "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "qdt_demo",
  "folder_name": "demo",
  "description": "Demo QGIS profile for QDT.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "qgisMinimumVersion": "3.28.0",
  "qgisMaximumVersion": "3.99.10",
  "version": "1.0.0",
  "plugins": [
    {
      "name": "Profile Manager",
      "folder_name": "profile-manager",
      "official_repository": true,
      "plugin_id": 2515,
      "version": "0.31"
    }
  ]
}

=== Guts/qgis-deployment-cli/tests/fixtures/profiles/good_profile_rules_never_deployed.json
{
    "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
    "name": "QDT excluded by rules",
    "folder_name": "qdt_never_deployed",
    "description": "QGIS profile made to demonstrate how rules engine can exclude a profile from deployment.",
    "author": "Julien Moura",
    "email": "qgis@oslandia.com",
    "qgisMinimumVersion": "3.34",
    "qgisMaximumVersion": "3.99",
    "version": "1.3.0",
    "plugins": [
        {
            "name": "QGIS Resource Sharing ",
            "folder_name": "qgis_resource_sharing",
            "location": "remote",
            "official_repository": true,
            "plugin_id": 2733,
            "version": "1.0.0"
        },
        {
            "name": "QTribu",
            "folder_name": "qtribu",
            "official_repository": true,
            "plugin_id": 2733,
            "version": "0.16.0"
        }
    ],
    "rules": [
        {
            "name": "To be not deployed",
            "description": "Rules defining that the profile is deployed only during the 1985 year.",
            "conditions": {
                "all": [
                    {
                        "path": "$.date.current_year",
                        "value": 1985,
                        "operator": "equal"
                    }
                ]
            }
        }
    ]
}

=== Guts/qgis-deployment-cli/examples/profiles/demo/profile.json
{
  "$schema": "https://raw.githubusercontent.com/qgis-deployment/qgis-deployment-toolbelt-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "qdt_demo",
  "folder_name": "demo",
  "description": "Demo QGIS profile for QDT.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "icon": "images/icon_shortcut_qdt_demo.ico",
  "qgisMinimumVersion": "3.28.0",
  "qgisMaximumVersion": "3.99.10",
  "version": "1.0.0",
  "plugins": [
    {
      "name": "Profile Manager",
      "folder_name": "profile-manager",
      "official_repository": true,
      "plugin_id": 2515,
      "version": "0.31"
    }
  ]
}

=== Guts/qgis-deployment-cli/tests/fixtures/profiles/good_profile_complete.json
{
  "name": "qdt_test_profile_complete",
  "alias": "Conférence QGIS FR",
  "description": "Profil de démonstration de la gestion des profils QGIS par Oslandia (atelier des journées QGIS FR 2022).",
  "author": "Benoît Ducarouge et Julien Moura",
  "email": "qgis@oslandia.com",
  "icon": "images/qgis_icon.ico",
  "splash": "images/splash_qgis-fr_600x287.png",
  "qgisMinimumVersion": "3.22",
  "qgisMaximumVersion": "3.30",
  "version": "1.1.0",
  "plugins": [
    {
      "name": "french_locator_filter",
      "version": "1.0.4",
      "url": "https://plugins.qgis.org/plugins/french_locator_filter/version/1.0.4/download/",
      "type": "remote",
      "plugin_id": 1846
    },
    {
      "name": "pg_metadata",
      "version": "1.2.1",
      "url": "https://plugins.qgis.org/plugins/pg_metadata/version/1.2.1/download/",
      "type": "remote"
    },
    {
      "name": "Layers menu from project",
      "version": "v2.0.6",
      "url": "https://plugins.qgis.org/plugins/menu_from_project/version/v2.0.6/download/",
      "type": "remote"
    },
    {
      "name": "Geotuileur",
      "version": "1.0.0",
      "url": "https://oslandia.gitlab.io/qgis/ign-geotuileur/geotuileur.1.0.0.zip",
      "location": "remote",
      "official_repository": false,
      "repository_url_xml": "https://oslandia.gitlab.io/qgis/ign-geotuileur/plugins.xml"
    }
  ]
}

=== Guts/qgis-deployment-cli/examples/profiles/only_linux/profile.json
{
  "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "QDT Only Linux",
  "folder_name": "qdt_only_linux",
  "description": "Demonstrating a QDT profile that's deployed only on Linux.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "qgisMinimumVersion": "3.34.0",
  "qgisMaximumVersion": "3.99.10",
  "version": "1.0.0",
  "rules": [
    {
      "name": "Environment",
      "description": "Profile is configured to run only on Linux.",
      "conditions": {
        "all": [
          {
            "path": "$.environment.operating_system_code",
            "value": "linux",
            "operator": "equal"
          },
          {
            "path": "$.date.current_year",
            "value": 2023,
            "operator": "greater_than_inclusive"
          }
        ]
      }
    }
  ]
}
